[browser.bookmark]
description = "Open bookmarks"
match = """
  (Open | show |) (all |) (bookmarks | bookmark )
"""

[[browser.bookmark.example]]
phrase = "Open bookmarks"

[[browser.bookmark.example]]
phrase = "bookmarks"
test = true

[[browser.bookmark.example]]
phrase = "Show bookmarks"
test = true

[[browser.bookmark.example]]
phrase = "Show all bookmarks"
test = true

[[browser.bookmark.example]]
phrase = "Show my bookmarks"
test = true

[[browser.bookmark.example]]
phrase = "Open bookmark"
test = true

[[browser.bookmark.example]]
phrase = "Show bookmark"
test = true

[browser.history]
description = "Open history"
match = """
  (Open | show |) (my browsing |) (all |) history
"""

[[browser.history.example]]
phrase = "Open history"

[[browser.history.example]]
phrase = "history"
test = true

[[browser.history.example]]
phrase = "my browsing history"
test = true

[[browser.history.example]]
phrase = "Show history"
test = true

[[browser.history.example]]
phrase = "Show all history"
test = true

[[browser.history.example]]
phrase = "Show my history"
test = true

[browser.preferences]
description = "open browser settings or preferences"
match = """
  (open |) (browser | firefox) (settings | preferences )
"""

[[browser.preferences.example]]
phrase = "open settings"

[[browser.preferences.example]]
phrase = "open firefox settings"
test = true

[[browser.preferences.example]]
phrase = "firefox settings"
test = true

[browser.addons]
description = "open browser addons or extensions"
match = """
  open (addons | addon | add-ons | add-on | extensions| extension |)
"""

[[browser.addons.example]]
phrase = "open addons"

[[browser.addons.example]]
phrase = "open extensions"
test = true

[[browser.addons.example]]
phrase = "open addons"
test = true

[[browser.addons.example]]
phrase = "open addon"
test = true

[[browser.addons.example]]
phrase = "open add-ons"
test = true

[[browser.addons.example]]
phrase = "open add-on"
test = true
