[window.switch]
description = "Switch the current window"
match = """
  (switch | activate | focus) (the | to |) next window [direction=next]
  (switch | activate | focus) (the | to |) (previous | last) window [direction=back]
"""

[window.downloads]
description = "Open the downloads"
match = """
  (show | open |) downloads (menu |)
"""
[[window.downloads.example]]
phrase = "open downloads"

[window.quitApplication]
description = "Close Firefox"
match = """
  (close | quit | exit | shutdown) (firefox | browser | the browser)
"""

[[window.quitApplication.example]]
phrase = "Close Firefox"

[window.combine]
description = "Combine all windows"
match = """
  combine all windows (into |) (one |) (window |)
  combine tabs (into |) (one |) window
"""

[[window.combine.example]]
phrase = "combine all windows"

[[window.combine.example]]
phrase = "combine all windows into one"
test = true

[[window.combine.example]]
phrase = "combine tabs into one window"
test = true

[window.close]
description = "Closes the window"
match = """
  close (the |) (this |) (all |) (window{s}) (for me |)
"""

[[window.close.example]]
phrase = "Close window"

[[window.close.example]]
phrase = "Close this window"
test = true

[[window.close.example]]
phrase = "Close all windows"
test = true

[window.zoom]
description = "Zooms the window"
match = """
  zoom (the |) (this |) window (for me |)
"""

[[window.zoom.example]]
phrase = "Zoom window"

[[window.zoom.example]]
phrase = "Zoom this window"
test = true

[window.minimize]
description = "Minimizes the window"
match = """
  (minimize | hide |) (the |) (this |) (window |) (for me |)
"""

[[window.minimize.example]]
phrase = "Minimize window"

[[window.minimize.example]]
phrase = "Minimize this window"
test = true

[[window.minimize.example]]
phrase = "Minimize"
test = true

[[window.minimize.example]]
phrase = "hide window"
test = true
