[self.cancelIntent]
description = "Cancels input, immediately closing the popup"
match = """
  cancel
  nevermind
  never mind
"""

[[self.cancelIntent.example]]
phrase = "nevermind"
test = true

[self.openIntentViewer]
description = "Opens the intent viewer (probably this page)"
match = """
  (show | open) all intents (for me |)
  (show | open) intent viewer (for me|)
"""

[self.openLexicon]
description = "Opens the lexicon: a hand-written help file that indicates things you can say"
match = """
  tell me about (this | firefox voice | this extension | voice)
  help
  what (else |) (can | should) (I | you) (do | say | ask) (you | from you | of you |)
  hi
  what commands (can | could | will | would |) (I | you |) (say | follow | use | speak |)
  (hello | hi |) how are you (doing |)
  show options
"""

[[self.openLexicon.example]]
phrase = "Tell me about Firefox Voice"

[[self.openLexicon.example]]
phrase = "Help"

[[self.openLexicon.example]]
phrase = "tell me about this"
test = true

[[self.openLexicon.example]]
phrase = "what can I do"
test = true

[[self.openLexicon.example]]
phrase = "what else can I say"
test = true

[[self.openLexicon.example]]
phrase = "what commands can you follow"
test = true

[[self.openLexicon.example]]
phrase = "hello how are you"
test = true

[[self.openLexicon.example]]
phrase = "What can I do?"

[[self.openLexicon.example]]
phrase = "what should I do"
test = true

[[self.openLexicon.example]]
phrase = "Show options"

[self.hello]
description = "Shows Lionel Richie's handsom face"
match = """
  hello
"""

[self.openOptions]
description = "Opens the options page"
match = """
  (open | open the | voice | firefox voice) (settings | options | preferences) (for me |)
  settings
  options
  preferences
"""

[[self.openOptions.example]]
phrase = "open settings for me"
test = true

[[self.openOptions.example]]
phrase = "voice settings"
test = true

[[self.openOptions.example]]
phrase = "firefox voice options"
test = true

[self.tellJoke]
description = "Someone asks for a joke or something funny"
match = """
  tell (me |) a joke
  say something funny
  make me laugh
"""

[[self.tellJoke.example]]
phrase = "Tell me a joke"

[[self.tellJoke.example]]
phrase = "Say something funny"

[[self.tellJoke.example]]
phrase = "Make me laugh"


[self.simpleTest]
description = "People often say 'test' to Firefox Voice. We should do a simple test to provide feedback"
match = """
  (this is | ) (test | testing) (test | testing |) (test | testing |)
"""

[[self.simpleTest.example]]
phrase = "test"

[self.helpIntent]
description = "This will try to find help for for the intent on lexicon page"
match = """
  (show | open |) (help | command{s}) (for | on | about |) [query] (to | for |) (me |)
"""

[[self.helpIntent.example]]
phrase = "help on search"

[self.smartSpeaker]
description = "This will enable or disable the wakeword and turn on or off audio output"
match = """
  (enable | turn on | activate | start) smart speaker (mode |) [activate=true]
  smart speaker (mode |) (on | active | activate | enabled | start) [activate=true]
  (disable | turn off | deactivate | stop) smart speaker (mode |) [activate=false]
  smart speaker (mode |) (off | deactivate | disabled | stop) [activate=false]
"""

[[self.smartSpeaker.example]]
phrase = "enable smart speaker mode"

[[self.smartSpeaker.example]]
phrase = "smart speaker off"
