[aliases]
# Each item is a possible word we'll see in the transcript, and the "correct" version of
# that word. I.e., if we see "open app" maybe the right transcription is "open tab"
# Note if you have a combined word that should be separated (e.g., "clicklink" should be "click link")
# that you'll need to put that into the pattern, and not here
app = "tab"
cat = "tab"
tap = "tab"
tech = "tab"
top = "tab"
in = "on"
nest = "next"
closest = "close"
closed = "close"
webpage = "page"
website = "site"
intense = "intents"
interns = "intents"
haste = "paste"
taste = "paste"
pace = "paste"
best = "paste"
coffee = "copy"
"down ward" = "downward"
"up ward" = "upward"
like = "link"
text = "next"
# Seems like a bad substitution, but see in the wild...
pooping = "open"
poop = "open"
pint = "pinned"
"book mark" = "bookmark"

[stopwords]
words = """
# Words from https://github.com/explosion/spaCy/blob/e0cf4796a505bd26e8fcb95d23b89fd7eca3be0a/spacy/lang/en/stop_words.py
a about above across after afterwards again against all almost alone along
already also although always am among amongst amount an and another any anyhow
anyone anything anyway anywhere are around as at
back be became because become becomes becoming been before beforehand behind
being below beside besides between beyond both bottom but by
call can cannot ca could
did do does doing done down due during
each eight either eleven else elsewhere empty enough even ever every
everyone everything everywhere except
few fifteen fifty first five for former formerly forty four from front full
further
get give go
had has have he hence her here hereafter hereby herein hereupon hers herself
him himself his how however hundred
i if in indeed into is it its itself
keep
last latter latterly least less
just
made make many may me meanwhile might mine more moreover most mostly move much
must my myself
# Removing 'not' since it seems important...
name namely neither never nevertheless next nine no nobody none noone nor
nothing now nowhere
of off often on once one only onto or other others otherwise our ours ourselves
out over own
part per perhaps please put
quite
rather re really regarding
same say see seem seemed seeming seems serious several she should show side
since six sixty so some somehow someone something sometime sometimes somewhere
still such
take ten than that the their them themselves then thence there thereafter
thereby therefore therein thereupon these they third this those though three
through throughout thru thus to together too top toward towards twelve twenty
two
under until up unless upon us used using
various very very via was we well were what whatever when whence whenever where
whereafter whereas whereby wherein whereupon wherever whether which while
whither who whoever whole whom whose why will with within without would
yet you your yours yourself yourselves
"""
