[search.next]
description = "If you've done a search then this will display the next search result. If the last search had a card, and no search result was opened, then this will open a new tab with the first search result."
match = """
  (search |) next (to view |) (search |) (result{s} | item{s} | page | article |)
"""

[[search.next.example]]
phrase = "next search item"
test = true

[[search.next.example]]
phrase = "next"
test = true

[[search.next.example]]
phrase = "next result result"
test = true

[[search.next.example]]
phrase = "text"
test = true

[[search.next.example]]
phrase = "next article"
test = true

[search.previous]
description = "If you've done a search then this will display the previous search result."
match = """
  (search |) previous (search |) (result{s} | item{s} | page | article |)
"""

[[search.previous.example]]
phrase = "previous search item"
test = true

[[search.previous.example]]
phrase = "previous"
test = true

[search.search]
description = "Experimental search interface; this does all searches in a special pinned tab, and if the search results in a card then a screenshot of the card is displayed in the popup. If there's no card, then the first search result is opened in a new tab."
match = """
  (do a |) (query | find | find me | look up | lookup | look on | look for) (the web | the internet |) (for |) [query] (on the web |) (for me |)
"""

[[search.search.example]]
phrase = "Look up recipes for fish tacos"

[[search.search.example]]
phrase = "Who created breaking bad?"

[[search.search.example]]
phrase = "Who won the World Series game last night?"

[[search.search.example]]
phrase = "How deep is the Marianas Trench?"

[[search.search.example]]
phrase = "Weather in Flagstaff, Arizona"

[[search.search.example]]
phrase = "What's the temperature in San Antonio?"

[[search.search.example]]
phrase = "What time is it?"

[[search.search.example]]
phrase = "What time is it in Berlin?"

[[search.search.example]]
phrase = "How long will it take to get to Springfield?"

[[search.search.example]]
phrase = "How do I get to the hardware store?"

[search.searchPage]
description = "Opens a search page"
match = """
  (do a |) (search | look on) (the web | the internet |) (for |) [query] (on the web |) (for me|)
"""

[[search.searchPage.example]]
phrase = "Search for hiking in Denver"

[[search.searchPage.example]]
phrase = "search for tops"

[[search.searchPage.example]]
phrase = "do a search for query on the web for me"
test = true
expectSlots = {query = "query"}

# FIXME: This is resolving as search.search, because it matches just as well as search.searchPage
# I'm not sure how to resolve this.
#[[search.searchPage.example]]
#phrase = "look on the web for query"
#test = true
#expectSlots = {query = "query"}

[search.show]
description = "Focuses the special tab used for searching"
match = """
  (open | show | focus) search (result{s} |)
  (open | show | focus) result{s}
"""

[[search.show.example]]
phrase = "open results"
test = true

[[search.show.example]]
phrase = "show search result"
test = true

[[search.show.example]]
phrase = "focus result"
test = true

[search.defaultSearchEngine]
description = "Opens the default search engine"
match = """
  search
"""

[[search.defaultSearchEngine.example]]
phrase = "search"
test = true

[search.searchGoogle]
description = "Give search results from google"
match = """
  (do a |) (search | search on | query | find | look up | lookup | look on |) (google) (for | for the |) [query] (for me |)
  (do a |) (search | query | find | look up | lookup | look on | look for |) (for | for the |) [query] (on |) (google) (for me |)
"""

[[search.searchGoogle.example]]
phrase = "google waterfall"
expectSlots = {query = "query"}

[[search.searchGoogle.example]]
phrase = "search for fox news on google"
expectSlots = {query = "query"}